Add "superordinate" param to univention_dictory_manager module
univention/ansible-modules pull request #9
Opened 2023-01-03 17:05 UTC by s3lph

Fixes #7

2023-01-09 11:16 UTC, Daenou requested changes

2023-01-09 11:16 UTC, Daenou commented on docs/univention_directory_manager.md
> +superordinate (string) | None | When creating a new object, set its superordinate to this DN. Only affects newly created LDAP objects, this option is ingored for modifications and removals of existin
```suggestion
superordinate (string) | None | When creating a new object, set its superordinate to this DN. Only affects newly created LDAP objects, this option is ignored for modifications and removals of existing entries.
```

2023-01-09 11:16 UTC, Daenou commented on plugins/modules/univention_directory_manager.py
> +            - Only affects newly created LDAP objects, this option is ingored for
```suggestion
            - Only affects newly created LDAP objects, this option is ignored for
```

2023-05-11 06:07 UTC, HunterZeroSix commented
Hi @s3lph ,
Thank you for your contribution.
I currently refactor the `univention_directory_manager` and will have a closer look on your PR.

2023-05-19 18:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/univention/ansible-modules?pullRequest=9) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/univention/ansible-modules?pullRequest=9) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/univention/ansible-modules?pullRequest=9) it.</sub>

2023-06-13 12:02 UTC, closed without merging